[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
adif = { path = "../adif" }
bincode = "2.0.1"
jiff = { version = "0.2.15", features = [ "serde" ] }
serde = "1.0.219"
sled = "0.34.7"
